apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
    version: $VERSION
  namespace: $NAMESPACE
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: $APP_NAME
          image: >-
            719012679654.dkr.ecr.eu-central-1.amazonaws.com/$APP_NAME:$TAG
          ports:
            - name: business
              containerPort: 8080
            - name: jmx
              containerPort: 9090
          imagePullPolicy: Always
          env:
            - name: SPRING_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: global-eviroments
                  key: env
            - name: JAVA_OPTS
              value: '-Xmx1G'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: jmx
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: jmx
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
          volumeMounts:
            - mountPath: /mnt/log
              name: log-pvc
      imagePullSecrets:
        - name: aws-registry
      volumes:
        - name: log-pvc
          hostPath:
            path: /opt/data/log-claim
            type: Directory
