apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{name}}
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{name}}
  endpoints:
    - port: jmx
      path: /actuator/prometheus
      interval: 10s
      honorLabels: true
