apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: demo
  endpoints:
    - port: jmx
      path: /actuator/prometheus
      interval: 10s
      honorLabels: true
