apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
  namespace: default
spec:
  selector:
    app: demo
  ports:
    - name: business
      protocol: TCP
      port: 8080
      targetPort: business
    - name: jmx
      protocol: TCP
      port: 9090
      targetPort: jmx
