# This is a basic workflow to help you get started with Actions

name: Deploy to DEV

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out deploy
      - name: Call deploy to DEV jenkins job
        uses: Atomanti007/jenkins-deploy-action@main
        with:
          user_name: ${{secrets.JENKINS_USER}}
          api_token: ${{secrets.JENKINS_TOKEN}}
          jenkins_url: ${{secrets.JENKINS_URL}}
          wait: false
          job_name: 'Bijo/job/Angular_Frontent_Deploy_to_DEV'

