apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  endpoints:
    - port: jmx
      path: /actuator/prometheus
      interval: 10s
      honorLabels: true
